### ISSUE TITLE
All links are dead

### ISSUE THREAD

**Issue by joos2010kj** [katha-ai/EmoTx-CVPR2023#12]
Hi,

It looks like all the shared links are dead or expired.  Could you update the link for each?

Thanks!

**Comment by dhruvhacks** [comment]
Thanks for pointing this out @joos2010kj , will resolve this issue with #11 .

**Comment by CeLuigi** [comment]
Hi,

At first, I thought they were just links to weights for extracting features, but none of the links are accessible.
Could you update the link for each?

Thanks
