### ISSUE TITLE
When to expect the trained models to be released?

### ISSUE THREAD

**Issue by iccv-clvl** [katha-ai/EmoTx-CVPR2023#3]
Hello, there
Thanks for the amazing work! I just wanted to ask whether you are planning to release the models and instructions soon. Any estimates? I am really interested in this work.
Looking forward to hearing from you soon.

Best,
Kilich

**Comment by dhruvhacks** [comment]
Hello Kilich,
Thank you for your kind words and your interest in our work!
While I don't have an exact timeline, I can assure you that we plan to share the instructions and pre-trained models soon.
I'm sorry for the delay. We encountered challenges in uploading and hosting the large 400+GB extracted features.

Tag: @iccv-clvl

**Comment by ghost** [comment]
Hi,
How do I get the experimental dataset? That helped me a lot. THANKS!

**Comment by dhruvhacks** [comment]
@GetLemonNow Will share the extracted features, soon!
