### ISSUE TITLE
What is the correct way to load pretrained models?

### ISSUE THREAD

**Issue by Kilichbek** [katha-ai/EmoTx-CVPR2023#6]
Hello, 
Thanks for your exciting work! 

I have a question regarding the correct way of loading the pretrained models. 
I am assuming that I can achieve via
```
# load model checkpoint if given
model_path = "EmoTx_Top25.pt"
model.load_state_dict(torch.load(model_path)["model_state_dict"])
model.eval()
```
however, I am receiving the following error: `ModuleNotFoundError: No module named 'M5_1'`

**Comment by dhruvhacks** [comment]
Hello @Kilichbek,
Thanks for pointing this out, it appears the checkpoints are referring to some obsolete keys. Will re-share the updated checkpoints!

**Comment by dhruvhacks** [comment]
Hey @Kilichbek ,
I have updated the model checkpoint links in #7 and added the instructions to load them in `README.md`, you may test it and LMK if you face any issues.

**Comment by Kilichbek** [comment]
Hi, Dhruv
Thanks for the updates. It has been resolved, but I have encountered another: 
`RuntimeError: The shape of the 2D attn_mask is torch.Size([650, 650]), but should be (1850, 1850).`
I am assuming that I am loading wrong features for pretrained models?
currently, I am using the following config setup 
```
# String variables
scene_feat_type: "mvit_v1" # "resnet50_places" # "generic"
face_feat_type: "resnet50_fer" # "emo" # "generic"
srt_feat_type: "independent" # "concat"
srt_feat_model: "roberta"
pkl_name: "2017-11-02-51-7637_py3.pkl"
```

**Comment by dhruvhacks** [comment]
Hey @Kilichbek ,
Took some time to figure out this little bug, I've updated the loading instructions and checkpoint links in the PR.
This sub-issue happened due to the default `max_individual_tokens=100` while defining the EmoTx model, whereas the checkpoint versions expect this value to be `300`.
The current checkpoints will work with the following snippet (new checkpoints have two new keys)-
```python
import torch
from models.emotx import EmoTx

model_checkpoint_filepath = "<PATH_TO_CHECKPOINT>.pt"
chkpt = torch.load(model_checkpoint_filepath)

model = EmoTx(
    num_labels=chkpt["num_labels"],
    num_pos_embeddings=chkpt["num_pos_embeddings"],
    scene_feat_dim=chkpt["scene_feat_dim"],
    char_feat_dim=chkpt["char_feat_dim"],
    srt_feat_dim=chkpt["srt_feat_dim"],
    num_chars=chkpt["num_chars"],
    num_enc_layers=chkpt["num_enc_layers"],
    max_individual_tokens=300, ##### NEW LINE
    hidden_dim=512  ##### NEW LINE
)
model.load_state_dict(chkpt["state_dict"])
```

**Comment by dhruvhacks** [comment]
Hey @Kilichbek ,
Feel free to re-open this, in case the new checkpoints have some issues.
Thanks!
